### ISSUE TITLE
[screenshot.js] Error loading textures

### ISSUE THREAD

**Issue by shketov** [PrismarineJS/prismarine-viewer#119] opened 2021-01-14 13:00 UTC
When I try to take a screenshot, I get an error that no. png file with textures was found at the specified path
```
Using version: 1.12
(node:2072) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\shketov\Desktop\Bot\node_modules\prismarine-viewer\public\textures\1.12.png'
    at setSource (C:\Users\shketov\Desktop\Bot\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\shketov\Desktop\Bot\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\shketov\Desktop\Bot\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\shketov\Desktop\Bot\node_modules\canvas\index.js:23:10)
    at loadTexture (C:\Users\shketov\Desktop\Bot\node_modules\prismarine-viewer\viewer\lib\utils.js:7:3)
    at WorldRenderer.setVersion (C:\Users\shketov\Desktop\Bot\node_modules\prismarine-viewer\viewer\lib\worldrenderer.js:61:5)
    at Viewer.setVersion (C:\Users\shketov\Desktop\Bot\node_modules\prismarine-viewer\viewer\lib\viewer.js:34:16)
    at Object.module.exports.main (C:\Users\shketov\Desktop\Bot\modules\screenshot.js:27:10)
    at C:\Users\shketov\Desktop\Bot\commands\help.js:17:16
```

![image](https://user-images.githubusercontent.com/56227259/104593950-81009100-5681-11eb-8bf4-a2c31b08b5ce.png)

**Comment by rom1504** [comment] 2021-01-14 15:47
duplicate of https://github.com/PrismarineJS/prismarine-viewer/issues/120

**Closed by rom1504** 2021-01-14 15:47 UTC
